### ISSUE TITLE
Upload entity_df from pandas dataframe not working with event timestamp columns

### ISSUE THREAD

**Issue by amommendes** [Shopify/feast-trino#24]
## Expected Behavior 

When using pandas dataframe with timestamp values in the `entity_df`, tge `get_historical_features` should work 

The error causes are the following:
- Cause 1 - `pa_to_trino_value_type` not mapping timestamp64 pandas type
- Cause 2 - Handling the above error, the timestamp values from entitiy_df needs to be handled when [inserting them on Trino](https://github.com/Shopify/feast-trino/blob/7bfc5ad02fbee6717ca44182df58cac2f4b9b22e/feast_trino/connectors/utils.py#L44), 

### Cause 1:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/feast_trino/connectors/utils.py", line 26, in get_trino_table_schema_from_dataframe
    trino_type = pa_to_trino_value_type(str(field.type))
  File "/usr/local/lib/python3.7/site-packages/feast_trino/trino_type_map.py", line 56, in pa_to_trino_value_type
    return type_map[pa_type_as_str]
KeyError: 'timestamp[ns]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_features.py", line 55, in <module>
    "driver_hourly_stats:avg_daily_trips",
  File "/usr/local/lib/python3.7/site-packages/feast/usage.py", line 280, in wrapper
    raise exc.with_traceback(traceback)
  File "/usr/local/lib/python3.7/site-packages/feast/usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/feast/feature_store.py", line 714, in get_historical_features
    full_feature_names,
  File "/usr/local/lib/python3.7/site-packages/feast/infra/passthrough_provider.py", line 174, in get_historical_features
    full_feature_names=full_feature_names,
  File "/usr/local/lib/python3.7/site-packages/feast_trino/trino.py", line 179, in get_historical_features
    client=client, table_name=table_reference, entity_df=entity_df,
  File "/usr/local/lib/python3.7/site-packages/feast_trino/trino.py", line 251, in _upload_entity_df_and_get_entity_schema
    client=client, df=entity_df, table_ref=table_name
  File "/usr/local/lib/python3.7/site-packages/feast_trino/connectors/memory.py", line 18, in upload_pandas_dataframe_to_trino
    table_ref=table_ref, schema=get_trino_table_schema_from_dataframe(df=df)
  File "/usr/local/lib/python3.7/site-packages/feast_trino/connectors/utils.py", line 29, in get_trino_table_schema_from_dataframe
    f"Not supported type '{field.type}' in entity_df for '{field.name}'."
ValueError: Not supported type 'timestamp[ns]' in entity_df for 'event_timestamp'.
```

#### PyArrow dtypes inference
**Pandas DF**
```python
driver_id                                      int64
label_driver_reported_satisfaction             int64
event_timestamp                       datetime64[ns]
dtype: object
```

**PyArrow table**
```
pyarrow.Field<driver_id: int64>
pyarrow.Field<label_driver_reported_satisfaction: int64>
pyarrow.Field<event_timestamp: timestamp[ns]>
```
### Cause 2:
If we handle the timestamp type (as proposed below), then we got the following error from Trino:
```java
io.trino.sql.parser.ParsingException: line 3:31: mismatched input '23'. Expecting: ')', ','
	at io.trino.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
```
This is because the method `format_pandas_row` does not quotes timestamp values:
```python
def format_pandas_row(df: pd.DataFrame) -> str:
    def _format_value(value: str) -> str:
        if isinstance(value, str):
            return f"'{value}'"
        else:
            return f"{value}"

    results = []
    for row in df.values:
        results.append(f"({','.join([_format_value(v) for v in row])})")
    return ",".join(results)
```

## Steps to reproduce
1 - With hive connector, create a hive table pointing out to the feast sample parquet, e.g.:
```sql
create table hive.feast.driver_hourly_stats (event_timestamp timestamp, driver_id integer,  conv_rate real, acc_rate real, avg_daily_trips integer, created timestamp) with (external_location='file:///path/to/sample/parquet', format='PARQUET');
```
2 - Create a sample entity dataframe and run get_historical_features

```python
entity_df = pd.DataFrame.from_dict(
    {
        "driver_id": [1001, 1002, 1003],
        "label_driver_reported_satisfaction": [1, 5, 3],
        "event_timestamp": [
            datetime.now() - timedelta(minutes=11),
            datetime.now() - timedelta(minutes=36),
            datetime.now() - timedelta(minutes=73),
        ],
    }
)

training_df = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "driver_hourly_stats:conv_rate",
        "driver_hourly_stats:acc_rate",
        "driver_hourly_stats:avg_daily_trips",
    ],
).to_df()
```
### Specifications

- Version: 
    - feast 0.15.0
    - Trino cluster 364
- Platform:
- Subsystem:

## Possible Solution
With new connectors added, I think these points will be solved. But these are possible solutions:
### Cause 1
Map timestamps types:
```python
def pa_to_trino_value_type(pa_type_as_str: str) -> str:
    # PyArrow types: https://arrow.apache.org/docs/python/api/datatypes.html
    # Trino type: https://trino.io/docs/current/language/types.html
    pa_type_as_str = pa_type_as_str.lower()

    if pa_type_as_str.startswith("date"):
        return "date"

    if pa_type_as_str.startswith("timestamp"):
        return "timestamp"

    if pa_type_as_str.startswith("decimal"):
        return pa_type_as_str

    if pa_type_as_str.startswith("dictionary<values=string,"):
        return "string"
```

### Cause 2:
```python
def format_pandas_row(df: pd.DataFrame) -> str:
    def _format_value(value: str) -> str:
        if isinstance(value, str):
            return f"'{value}'"
        elif "timestamp" in str(type(value)).lower():
            return f"cast('{value}' as timestamp)"
        else:
            return f"{value}"
```

**Comment by MattDelac** [comment]
I think that should be fixed in the following PR https://github.com/Shopify/feast-trino/pull/22/files#diff-025f06fbd0e7e5310308193c59a581c7aee01366dcde09191710c26345e972ffR36-R41

**Comment by MattDelac** [comment]
@amommendes Can you check since the relevant PRs got merged ?

Thanks

**Comment by amommendes** [comment]
> @amommendes Can you check since the relevant PRs got merged ?
> 
> Thanks

Sure @MattDelac , about this issue specifically the type handling worked well... Then I will close this issue, thanks
